### PR TITLE
[Feature #161046415] Added login page and styling

### PR DESCRIPTION
**Pull request by eduhmik**
**What does this PR do?**
Create login page and style it with CSS

**Description of task to be completed**
User login page to help store owners and attendants login into the system.

**How should this be manually tested?**
clone this repo and checkout to ft-login-page-ui-161046415
Open login.html in a browser

**Any background context you want to provide?**
none

**What are the relevant pivotal tracker stories?**
#161046415

**Screenshots (if appropriate)**
login

### CODE REVIEW

**Comment by waracci** [comment]
Good job :+1:  but there is no need for the square brackets on the PR name.
So instead of 

>[Feature #161046415] Added login page and styling

it should be :

>  #161046415 Added login page and styling

**Comment by eduhmik** [comment]
Thanks for the feedback

**Comment by waracci** [comment]
@eduhmik Also, are you sure you want to merge this PR into master branch? Shouldn't you merge it into develop/development/UI?

**Comment by eduhmik** [comment]
Yes, I just realized that mistake from kwame's PR. I had a develop branch I don't understand why it was not pushed to remote

**Comment by eduhmik** [comment]
Reviewed the feedback. Thanks @waracci

**Comment by kwanj-k** [comment]
Nice UI man
one question though
why 'let me In' instead of just login

**Comment by eduhmik** [comment]
> 
> 
> Nice UI man
> one question though
> why 'let me In' instead of just login

Haha... no reason just s different phrase with the same meaning

**Pull request merged**
